#!/busybox ash

# Set up environment
/busybox mkdir -p /bin
/busybox --install -s /bin

mkdir -p /proc /dev /sys /host9p
mount -a

command=$(awk '{ for(i = 1; i <= NF; i++) { if ($i ~ /^command=/) { print substr($i, 9); exit } } }' < /proc/cmdline)

mount -o move sys host9p/sys
mount -o move proc host9p/proc
mount -o move dev host9p/dev

exec switch_root host9p "$command"
