name: images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  config:
    name: Read kernel versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.kernel.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Kernel Test Matrix
      id: kernel
      uses: ./matrix

  kernel:
    name: Kernel
    needs: config
    uses: ./.github/workflows/build-and-push.yml
    strategy:
      matrix:
        include: ${{ fromJSON(needs.config.outputs.matrix) }}
    with:
      kernel_version: ${{ matrix.version }}
      image_tag: ${{ matrix.image_tag }}

  results:
    # Always run, even if kernel job fails.
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Results
    needs: kernel
    steps:
    - run: exit 1
      if: ${{ needs.kernel.result != 'success' }}
